/**
 * The icon set and the store artwork, task T-504.
 *
 *   node scripts/gen-assets.mjs
 *
 * One SVG is the source, `assets/icon.svg`, rendered by the same Chromium the
 * smoke run uses. Generated rather than committed as opaque binaries so the mark
 * can be reasoned about, reproduced and changed in one place. The script skips
 * cleanly when Playwright is not installed: the PNGs it writes are committed, so
 * a contributor never has to run it.
 *
 * Store screenshots are not generated here. They are pictures of the real
 * interface, and `npm run smoke` already takes them.
 */
import { execSync } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, readdirSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const require = createRequire(import.meta.url);

let chromium;
try {
  const globalRoot = execSync("npm root -g", { encoding: "utf8" }).trim();
  ({ chromium } = require(require.resolve("playwright", { paths: [globalRoot, root] })));
} catch {
  console.log("assets: playwright is not installed, skipping");
  process.exit(0);
}

const ICON_SIZES = [16, 32, 48, 128];

/**
 * What each store asks for. Chrome and Edge both take the small tile; the
 * marquee is Chrome's, and Edge's listing uses the 300 by 300 logo.
 */
const TILES = [
  { name: "promo-small-440x280.png", width: 440, height: 280, icon: 128, label: true },
  { name: "promo-marquee-1400x560.png", width: 1400, height: 560, icon: 240, label: true },
  { name: "logo-300x300.png", width: 300, height: 300, icon: 220, label: false },
];

/**
 * The full Chromium Playwright downloaded, rather than its headless shell: the
 * shell build is not always present, and the smoke run already relies on this
 * one being there.
 */
function findBundledChromium() {
  const base = path.join(homedir(), ".cache", "ms-playwright");
  if (!existsSync(base)) return null;
  for (const build of readdirSync(base)
    .filter((name) => /^chromium-\d+$/.test(name))
    .sort((a, b) => Number(b.split("-")[1]) - Number(a.split("-")[1]))) {
    for (const candidate of [
      path.join(base, build, "chrome-linux64", "chrome"),
      path.join(base, build, "chrome-mac", "Chromium.app", "Contents", "MacOS", "Chromium"),
    ]) {
      if (existsSync(candidate)) return candidate;
    }
  }
  return null;
}

const svg = await readFile(path.join(root, "assets", "icon.svg"), "utf8");
const executablePath = findBundledChromium();
const browser = await chromium.launch({
  headless: true,
  ...(executablePath ? { executablePath } : {}),
});
const page = await browser.newPage();

try {
  const iconDir = path.join(root, "assets", "icons");
  await mkdir(iconDir, { recursive: true });
  for (const size of ICON_SIZES) {
    await page.setViewportSize({ width: size, height: size });
    await page.setContent(shell(`<div class="icon">${svg}</div>`, size), { waitUntil: "load" });
    await page.locator(".icon").screenshot({
      path: path.join(iconDir, `icon-${size}.png`),
      omitBackground: true,
    });
    console.log(`assets: icons/icon-${size}.png`);
  }

  const storeDir = path.join(root, "assets", "store");
  await mkdir(storeDir, { recursive: true });
  for (const tile of TILES) {
    await page.setViewportSize({ width: tile.width, height: tile.height });
    await page.setContent(tilePage(svg, tile), { waitUntil: "load" });
    await page.screenshot({ path: path.join(storeDir, tile.name) });
    console.log(`assets: store/${tile.name}`);
  }

  await writeFile(
    path.join(storeDir, "README.md"),
    `# Store artwork\n\nGenerated by \`node scripts/gen-assets.mjs\` from \`assets/icon.svg\`. Never edited by hand.\n\nScreenshots of the interface are taken by \`npm run smoke\`, which writes them to\n\`.tmp/shots\`. The store listings in \`docs/store/\` say which ones each store wants.\n`,
    "utf8",
  );
} finally {
  await browser.close();
}

function shell(body, size) {
  return `<!doctype html><meta charset="utf-8"><style>
    html,body{margin:0;padding:0;background:transparent}
    .icon,.icon svg{width:${size}px;height:${size}px;display:block}
  </style>${body}`;
}

function tilePage(icon, tile) {
  const wordmark = tile.label
    ? `<div class="words"><div class="name">TabsPack</div><div class="line">Export, move and restore your tabs. Any browser, one open file.</div></div>`
    : "";
  return `<!doctype html><meta charset="utf-8"><style>
    html,body{margin:0;padding:0;width:${tile.width}px;height:${tile.height}px;
      background:linear-gradient(135deg,#f7f8fa 0%,#eaf0fe 100%);
      font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Ubuntu,sans-serif;color:#16181c}
    .wrap{height:100%;display:flex;align-items:center;justify-content:center;gap:${Math.round(tile.icon / 4)}px;padding:0 ${Math.round(tile.width * 0.06)}px;box-sizing:border-box}
    .mark,.mark svg{width:${tile.icon}px;height:${tile.icon}px;display:block}
    .name{font-size:${Math.round(tile.icon * 0.42)}px;font-weight:600;letter-spacing:-0.02em}
    .line{font-size:${Math.round(tile.icon * 0.15)}px;color:#5b616e;margin-top:${Math.round(tile.icon * 0.06)}px;max-width:${Math.round(tile.width * 0.52)}px;line-height:1.35}
  </style><div class="wrap"><div class="mark">${icon}</div>${wordmark}</div>`;
}
