/**
 * The icon set and the store artwork, tasks T-504 and T-713.
 *
 *   node scripts/gen-assets.mjs
 *
 * One master is the source, `assets/icon.png` at 512 px, rendered down by the
 * same Chromium the smoke run uses. Everything derived lives in one place and
 * can be reproduced from one file.
 *
 * **Why a raster master rather than the SVG it used to be.** The chosen mark is
 * an illustration: a fan of coloured tabs, a window with depth, a gradient
 * arrow. Redrawing it as a vector was tried twice and came out worse both
 * times, thinner and emptier than the artwork it was copying, which is a
 * perfectly ordinary outcome when the design is illustrative rather than
 * geometric. A 512 px master downsamples to 128 with nothing lost and, with the
 * sharpening pass below, beats the vector at 16 as well. The original artwork
 * and the comparison that settled it are in `assets/candidates/reference/`.
 *
 * **The sharpening pass.** Any downscale to 16 px is soft, and a soft toolbar
 * icon looks like a mistake. After drawing the master into a canvas at the
 * target size, a small unsharp kernel is run over it in the page. It is applied
 * hardest at 16 and 32, where the loss is, and gently above that.
 *
 * The script skips cleanly when Playwright is not installed: the PNGs it writes
 * are committed, so a contributor never has to run it.
 *
 * Store screenshots are not generated here. They are pictures of the real
 * interface, and `npm run smoke` already takes them.
 */
import { execSync } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, readdirSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const require = createRequire(import.meta.url);

let chromium;
try {
  const globalRoot = execSync("npm root -g", { encoding: "utf8" }).trim();
  ({ chromium } = require(require.resolve("playwright", { paths: [globalRoot, root] })));
} catch {
  console.log("assets: playwright is not installed, skipping");
  process.exit(0);
}

const ICON_SIZES = [16, 32, 48, 128];

/**
 * What each store asks for. Chrome and Edge both take the small tile; the
 * marquee is Chrome's, and Edge's listing uses the 300 by 300 logo.
 */
const TILES = [
  { name: "promo-small-440x280.png", width: 440, height: 280, icon: 128, label: true },
  { name: "promo-marquee-1400x560.png", width: 1400, height: 560, icon: 240, label: true },
  { name: "logo-300x300.png", width: 300, height: 300, icon: 220, label: false },
];

/**
 * The full Chromium Playwright downloaded, rather than its headless shell: the
 * shell build is not always present, and the smoke run already relies on this
 * one being there.
 */
function findBundledChromium() {
  const base = path.join(homedir(), ".cache", "ms-playwright");
  if (!existsSync(base)) return null;
  for (const build of readdirSync(base)
    .filter((name) => /^chromium-\d+$/.test(name))
    .sort((a, b) => Number(b.split("-")[1]) - Number(a.split("-")[1]))) {
    for (const candidate of [
      path.join(base, build, "chrome-linux64", "chrome"),
      path.join(base, build, "chrome-mac", "Chromium.app", "Contents", "MacOS", "Chromium"),
    ]) {
      if (existsSync(candidate)) return candidate;
    }
  }
  return null;
}

/** The master, inlined as a data URI so the page needs no server and no file access. */
const master = `data:image/png;base64,${(await readFile(path.join(root, "assets", "icon.png"))).toString("base64")}`;
const executablePath = findBundledChromium();
const browser = await chromium.launch({
  headless: true,
  ...(executablePath ? { executablePath } : {}),
});
const page = await browser.newPage();

try {
  const iconDir = path.join(root, "assets", "icons");
  await mkdir(iconDir, { recursive: true });
  for (const size of ICON_SIZES) {
    await page.setViewportSize({ width: Math.max(size, 64), height: Math.max(size, 64) });
    await page.setContent(shell(size), { waitUntil: "load" });
    const encoded = await page.evaluate(() => window.render());
    await writeFile(path.join(iconDir, `icon-${size}.png`), Buffer.from(encoded, "base64"));
    console.log(`assets: icons/icon-${size}.png`);
  }

  const storeDir = path.join(root, "assets", "store");
  await mkdir(storeDir, { recursive: true });
  for (const tile of TILES) {
    await page.setViewportSize({ width: tile.width, height: tile.height });
    await page.setContent(tilePage(master, tile), { waitUntil: "load" });
    await page.screenshot({ path: path.join(storeDir, tile.name) });
    console.log(`assets: store/${tile.name}`);
  }

  await writeFile(
    path.join(storeDir, "README.md"),
    `# Store artwork\n\nGenerated by \`node scripts/gen-assets.mjs\` from \`assets/icon.png\`. Never edited by hand.\n\nScreenshots of the interface are taken by \`npm run smoke\`, which writes them to\n\`.tmp/shots\`. The store listings in \`docs/store/\` say which ones each store wants.\n`,
    "utf8",
  );
} finally {
  await browser.close();
}

/**
 * Draws the master at `size`, sharpens it, and hands back a base64 PNG.
 *
 * Done on a canvas rather than by screenshotting a scaled `<img>` because the
 * browser gives no control over the resample there, and because the unsharp
 * pass needs the pixels. `imageSmoothingQuality` high is a Lanczos-like
 * downscale; the kernel after it puts back the edge the downscale took off.
 */
function shell(size) {
  // Hardest where the loss is. Above 48 the master is barely being reduced.
  const amount = size <= 16 ? 0.9 : size <= 32 ? 0.7 : size <= 48 ? 0.4 : 0;
  return `<!doctype html><meta charset="utf-8"><style>html,body{margin:0;background:transparent}</style>
<script>
  window.render = () => new Promise((resolve) => {
    const image = new Image();
    image.onload = () => {
      const size = ${size};
      const canvas = document.createElement("canvas");
      canvas.width = canvas.height = size;
      const ctx = canvas.getContext("2d");
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = "high";
      ctx.drawImage(image, 0, 0, size, size);

      const amount = ${amount};
      if (amount > 0) {
        const src = ctx.getImageData(0, 0, size, size);
        const out = ctx.createImageData(size, size);
        const at = (x, y, c) =>
          src.data[(Math.min(size - 1, Math.max(0, y)) * size + Math.min(size - 1, Math.max(0, x))) * 4 + c];
        for (let y = 0; y < size; y += 1) {
          for (let x = 0; x < size; x += 1) {
            const i = (y * size + x) * 4;
            for (let c = 0; c < 3; c += 1) {
              // A 3x3 blur, then the original plus the difference: unsharp.
              let blur = 0;
              for (let dy = -1; dy <= 1; dy += 1) {
                for (let dx = -1; dx <= 1; dx += 1) blur += at(x + dx, y + dy, c);
              }
              blur /= 9;
              const value = at(x, y, c) + (at(x, y, c) - blur) * amount;
              out.data[i + c] = Math.max(0, Math.min(255, value));
            }
            // Alpha is left exactly as the downscale produced it. Sharpening it
            // would put a hard fringe on the rounded corners.
            out.data[i + 3] = src.data[i + 3];
          }
        }
        ctx.putImageData(out, 0, 0);
      }
      resolve(canvas.toDataURL("image/png").split(",")[1]);
    };
    image.src = ${JSON.stringify(master)};
  });
</script>`;
}

function tilePage(iconUri, tile) {
  const wordmark = tile.label
    ? `<div class="words"><div class="name">TabsPack</div><div class="line">Export, move and restore your tabs. Any browser, one open file.</div></div>`
    : "";
  return `<!doctype html><meta charset="utf-8"><style>
    html,body{margin:0;padding:0;width:${tile.width}px;height:${tile.height}px;
      background:linear-gradient(135deg,#f7f8fa 0%,#eaf0fe 100%);
      font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Ubuntu,sans-serif;color:#16181c}
    .wrap{height:100%;display:flex;align-items:center;justify-content:center;gap:${Math.round(tile.icon / 4)}px;padding:0 ${Math.round(tile.width * 0.06)}px;box-sizing:border-box}
    .mark{width:${tile.icon}px;height:${tile.icon}px;display:block}
    .name{font-size:${Math.round(tile.icon * 0.42)}px;font-weight:600;letter-spacing:-0.02em}
    .line{font-size:${Math.round(tile.icon * 0.15)}px;color:#5b616e;margin-top:${Math.round(tile.icon * 0.06)}px;max-width:${Math.round(tile.width * 0.52)}px;line-height:1.35}
  </style><div class="wrap"><img class="mark" src="${iconUri}" alt="" />${wordmark}</div>`;
}
